build:
  verbosity: detailed

branches:
  only:
    - master

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

build_script:
  - ./gradlew clean -i -Dtest.single=XCUITModeTest test

matrix:
  fast_finish: true
