/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.appium.java_client.windows;

import io.appium.java_client.AppiumClientConfig;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.CommandExecutionHelper;
import io.appium.java_client.PullsFiles;
import io.appium.java_client.PushesFiles;
import io.appium.java_client.http.HttpClient;
import io.appium.java_client.remote.AppiumCommandExecutor;
import io.appium.java_client.remote.AutomationName;
import io.appium.java_client.screenrecording.CanRecordScreen;
import io.appium.java_client.service.local.AppiumDriverLocalService;
import io.appium.java_client.service.local.AppiumServiceBuilder;
import org.jspecify.annotations.Nullable;
import org.openqa.selenium.Capabilities;
import org.openqa.selenium.Platform;

import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Map;

import static io.appium.java_client.MobileCommand.PULL_FILE;
import static io.appium.java_client.MobileCommand.PULL_FOLDER;
import static io.appium.java_client.MobileCommand.PUSH_FILE;
import static java.util.Objects.requireNonNull;

public class WindowsDriver extends AppiumDriver implements
        PullsFiles,
        PushesFiles,
        CanRecordScreen {
    private static final String PLATFORM_NAME = Platform.WINDOWS.name();
    private static final String AUTOMATION_NAME = AutomationName.WINDOWS;

    public WindowsDriver(AppiumCommandExecutor executor, Capabilities capabilities) {
        super(executor, ensurePlatformAndAutomationNames(capabilities, PLATFORM_NAME, AUTOMATION_NAME));
    }

    public WindowsDriver(URL remoteAddress, Capabilities capabilities) {
        super(remoteAddress, ensurePlatformAndAutomationNames(
                capabilities, PLATFORM_NAME, AUTOMATION_NAME));
    }

    public WindowsDriver(URL remoteAddress, HttpClient.Factory httpClientFactory, Capabilities capabilities) {
        super(remoteAddress, httpClientFactory, ensurePlatformAndAutomationNames(
                capabilities, PLATFORM_NAME, AUTOMATION_NAME));
    }

    public WindowsDriver(AppiumDriverLocalService service, Capabilities capabilities) {
        super(service, ensurePlatformAndAutomationNames(capabilities, PLATFORM_NAME, AUTOMATION_NAME));
    }

    public WindowsDriver(AppiumDriverLocalService service, HttpClient.Factory httpClientFactory,
                         Capabilities capabilities) {
        super(service, httpClientFactory, ensurePlatformAndAutomationNames(
                capabilities, PLATFORM_NAME, AUTOMATION_NAME));
    }

    public WindowsDriver(AppiumServiceBuilder builder, Capabilities capabilities) {
        super(builder, ensurePlatformAndAutomationNames(capabilities, PLATFORM_NAME, AUTOMATION_NAME));
    }

    public WindowsDriver(AppiumServiceBuilder builder, HttpClient.Factory httpClientFactory,
                         Capabilities capabilities) {
        super(builder, httpClientFactory, ensurePlatformAndAutomationNames(
                capabilities, PLATFORM_NAME, AUTOMATION_NAME));
    }

    public WindowsDriver(HttpClient.Factory httpClientFactory, Capabilities capabilities) {
        super(httpClientFactory, ensurePlatformAndAutomationNames(
                capabilities, PLATFORM_NAME, AUTOMATION_NAME));
    }

    public WindowsDriver(URL remoteSessionAddress) {
        super(remoteSessionAddress, PLATFORM_NAME, AUTOMATION_NAME);
    }

    /**
     * Creates a new instance based on the given AppiumClientConfig and {@code capabilities}.
     * The HTTP client is default client generated by {@link HttpClient.Factory#createDefault()}.
     * For example:
     *
     * <pre>
     *
     * AppiumClientConfig appiumClientConfig = AppiumClientConfig.defaultConfig()
     *     .directConnect(true)
     *     .baseUri(URI.create("WebDriver URL"))
     *     .readTimeout(Duration.ofMinutes(5));
     * WindowsOptions options = new WindowsOptions();
     * WindowsDriver driver = new WindowsDriver(appiumClientConfig, options);
     *
     * </pre>
     *
     * @param appiumClientConfig take a look at {@link AppiumClientConfig}
     * @param capabilities take a look at {@link Capabilities}
     *
     */
    public WindowsDriver(AppiumClientConfig appiumClientConfig, Capabilities capabilities) {
        super(appiumClientConfig, ensurePlatformAndAutomationNames(
                capabilities, PLATFORM_NAME, AUTOMATION_NAME));
    }

    public WindowsDriver(Capabilities capabilities) {
        super(ensurePlatformAndAutomationNames(capabilities, PLATFORM_NAME, AUTOMATION_NAME));
    }

    /**
     * Pulls a file from the remote system. The Windows driver has no `mobile:` extension for it.
     *
     * @param remotePath Path to the file to read data from the remote device.
     * @return A byte array of Base64 encoded data.
     */
    @Override
    public byte[] pullFile(String remotePath) {
        return decodeBase64(CommandExecutionHelper.execute(this, Map.entry(PULL_FILE, Map.of("path", remotePath))));
    }

    /**
     * Pulls the content of a folder from the remote system. The Windows driver has no `mobile:` extension for it.
     *
     * @param remotePath Path to the folder to read data from the remote device.
     * @return A byte array of Base64 encoded zip archive data.
     */
    @Override
    public byte[] pullFolder(String remotePath) {
        return decodeBase64(CommandExecutionHelper.execute(this, Map.entry(PULL_FOLDER, Map.of("path", remotePath))));
    }

    /**
     * Saves base64-encoded data as a file on the remote system. The Windows driver has no `mobile:` extension for it.
     *
     * @param remotePath Path to the file to write data to on the remote device.
     * @param base64Data Base64 encoded byte array of the data to write to the remote device.
     */
    @Override
    public void pushFile(String remotePath, byte[] base64Data) {
        CommandExecutionHelper.execute(this, Map.entry(PUSH_FILE, Map.of(
                "path", remotePath,
                "data", new String(base64Data, StandardCharsets.UTF_8)
        )));
    }

    private static byte[] decodeBase64(@Nullable String base64String) {
        return Base64.getDecoder().decode(requireNonNull(base64String).getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Launch the application app under test after it was closed.
     */
    public void launchApp() {
        CommandExecutionHelper.executeScript(this, "windows: launchApp");
    }

    /**
     * Close the app under test.
     */
    public void closeApp() {
        CommandExecutionHelper.executeScript(this, "windows: closeApp");
    }
}
