version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-node8-alpha

    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew

      - run:
          command: echo y | android update sdk -u -a -t tools
      - run:
          command: echo y | android update sdk -u -a -t platform-tools
      - run:
          command: echo y | android update sdk -u -a -t build-tools-25.0.2
      - run:
          command: echo y | android update sdk -u -a -t android-25
      - run:
          command: echo y | android update sdk -u -a -t extra-google-m2repository
      - run:
          command: echo y | node --version
      - run:
          command: echo y | npm --version
      - run:
          command: sudo chmod 777 /home/circleci/code/
                    sudo npm install appium
      - run:
          command: echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
      - run:
          command: echo y | adb devices
      - run:
          name: Run Tests
          command: ./gradlew clean build uiAutomationTest -x test -x signArchives
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

